name: Generate Sentences PDF to verify correctness of vocabulary examples.

on:
  workflow_dispatch:
    inputs:
      kanji:
        description: 'Comma-separated kanji list to output debugging PDFs for.'
        default: 'all'
        required: true
        type: string

permissions:
  contents: write

env:
  KANJI: ${{ github.event.inputs.kanji || 'all' }}

jobs:
  generate_contents:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf
          wkhtmltopdf --version
          
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script to generate all sentences
        if: env.KANJI == 'all'
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE }}
          FOLDER_ID: ${{ secrets.FOLDER_ID }}
        run: |
          python main.py --sentences
          echo "List artifacts dir:"
          ls -al ./.artifacts

      - name: Run Python script to generate selected sentences
        if: env.KANJI != 'all'
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE }}
          FOLDER_ID: ${{ secrets.FOLDER_ID }}
        run: |
          python main.py --sentences-from "$KANJI"
          echo "List artifacts dir:"
          ls -al ./.artifacts

      - name: Store sentences (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: datasets-pdf
          path: ./.artifacts
          retention-days: 5
          if-no-files-found: error
          include-hidden-files: true
          overwrite: true